# Generated by Django 4.0.3 on 2022-03-23 20:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idBodega', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('fechaFactura', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 23, 20, 50, 52, 695032, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 23, 20, 50, 52, 695646, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 23, 20, 50, 52, 693654, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('idReferencia', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ean13', models.CharField(max_length=50)),
                ('ean8', models.CharField(max_length=50)),
                ('ean128', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('idSede', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMov',
            fields=[
                ('idTipoMov', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_mov', models.CharField(max_length=50)),
                ('signo', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('idUnidad', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tipo_unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PedidosMov',
            fields=[
                ('idNumero', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 23, 20, 50, 52, 695986, tzinfo=utc))),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.pedido')),
                ('idReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.reference')),
                ('idUnidadCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.tipounidad')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.proveedor'),
        ),
        migrations.CreateModel(
            name='MovInventario',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fechaMov', models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 23, 20, 50, 52, 697319, tzinfo=utc))),
                ('idBodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.bodega')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.factura')),
                ('idReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.reference')),
                ('idTipoMov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.tipomov')),
                ('idTipoUnidadMov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.tipounidad')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(verbose_name='Saldo')),
                ('idReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.reference')),
                ('idbodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasMov',
            fields=[
                ('idNumero', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedido', models.DateTimeField(auto_now_add=True)),
                ('ideReferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.reference')),
                ('idfactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.factura')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.factura')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.proveedor'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='idSede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.sede'),
        ),
    ]
