# Generated by Django 4.0.3 on 2022-04-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='codigo_dane_ciudad',
            field=models.CharField(max_length=3),
        ),
    ]
