# Generated by Django 4.0.4 on 2022-04-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('transporte', models.CharField(max_length=100, verbose_name='Transportadora')),
                ('factura_prov', models.CharField(max_length=50, verbose_name='Factura Recibida')),
                ('bodega_des', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmi.bodega', verbose_name='Bodega Destino')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmi.proveedor', verbose_name='Proveedor')),
                ('sede_ing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmi.sede')),
            ],
            options={
                'verbose_name': 'Ingreso de Referencias',
                'verbose_name_plural': 'Ingresos de Referencias',
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('transporte', models.CharField(max_length=100, verbose_name='Transportadora')),
                ('bodega_des', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmi.bodega', verbose_name='Bodega Destino')),
                ('sede_sal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmi.sede')),
            ],
            options={
                'verbose_name': 'Salida de Referencia',
                'verbose_name_plural': 'Salidas de Referencias',
            },
        ),
        migrations.CreateModel(
            name='SalidaRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('transporte', models.CharField(max_length=100, verbose_name='Transportadora')),
                ('bodega_des', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vmi.bodega', verbose_name='Bodega Destino')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.salida')),
            ],
            options={
                'verbose_name': 'Referencia de Salida',
                'verbose_name_plural': 'Referencias de Salidas',
            },
        ),
        migrations.CreateModel(
            name='IngresoRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empaque', models.CharField(max_length=30, verbose_name='Empaque/Embalaje en General')),
                ('lote', models.CharField(max_length=8, verbose_name='Lote de paquete')),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Referencia Recibida')),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('integridad', models.CharField(max_length=5, verbose_name='Integridad de la Referencia')),
                ('apariencia', models.CharField(max_length=5, verbose_name='Apariencia de la Referencia')),
                ('temp', models.CharField(max_length=2, verbose_name='Temperatura de Almacenamiento')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.ingreso', verbose_name='Factura de Ingreso')),
                ('referencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.referencia')),
                ('tipo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.unidadtipo')),
            ],
            options={
                'verbose_name': 'Referencia de Ingreso',
                'verbose_name_plural': 'Referencias de Ingresos',
            },
        ),
    ]
