# Generated by Django 4.0.4 on 2022-04-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0002_ingreso_salida_salidaref_ingresoref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoref',
            old_name='referencia_id',
            new_name='referencia',
        ),
    ]
