# Generated by Django 4.0.3 on 2022-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0002_alter_ciudad_options_alter_pais_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='codigo_dane_ciudad',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo_dane_departamento',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_orden',
            field=models.CharField(choices=[('A', 'Activo'), ('E', 'En Curso'), ('C', 'Cancelado'), ('P', 'Pago')], default='A', max_length=1),
        ),
    ]
