# Generated by Django 4.0.3 on 2022-04-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0002_alter_ciudad_codigo_dane_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(default='none', max_length=50, verbose_name='Dirección'),
        ),
    ]
