# Generated by Django 4.0.3 on 2022-04-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0002_typeunit_reference_provider_billing_movementbilling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='movementbilling',
            name='referencia_id',
        ),
        migrations.AddField(
            model_name='movementbilling',
            name='referencia_id',
            field=models.ManyToManyField(to='vmi.reference'),
        ),
        migrations.CreateModel(
            name='MovementOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmi.order')),
            ],
            bases=('vmi.order',),
        ),
        migrations.CreateModel(
            name='ProviderOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vmi.order')),
            ],
            bases=('vmi.order',),
        ),
    ]
