# Generated by Django 4.0.3 on 2022-04-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0003_sede_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='estado_sede',
            field=models.CharField(choices=[('O', 'Operativo'), ('F', 'Fuera de Servicio'), ('T', 'Traslado')], default='O', max_length=1, verbose_name='Estado de Sede'),
        ),
    ]
