# Generated by Django 4.0.3 on 2022-03-24 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0004_alter_factura_fechafactura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('idReferencia', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ean13', models.CharField(max_length=50)),
                ('ean8', models.CharField(max_length=50)),
                ('ean128', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bodega',
            name='idBodega',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaFactura',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 13, 38, 34, 862996, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idFactura',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movinventario',
            name='fechaMov',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 13, 38, 34, 864491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 13, 38, 34, 863346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidosmov',
            name='fecha_pedido',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 13, 38, 34, 863555, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidosmov',
            name='idNumero',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 13, 38, 34, 861708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='idProveedor',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sede',
            name='idSede',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipounidad',
            name='idUnidad',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facturasmov',
            name='ideReferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.referencia'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='idReferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.referencia'),
        ),
        migrations.AlterField(
            model_name='movinventario',
            name='idReferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.referencia'),
        ),
        migrations.AlterField(
            model_name='pedidosmov',
            name='idReferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.referencia'),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
