# Generated by Django 4.0.3 on 2022-04-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0004_alter_bodega_estado_facturaenc_facturadet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inhabilitado', 'Inhabilitado'), ('Atrasado', 'Atrasado')], default='A', max_length=20, verbose_name='Estado de la Bodega'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='estado_sede',
            field=models.CharField(choices=[('A', 'Activo'), ('F', 'Fuera de Servicio'), ('T', 'Traslado')], default='A', max_length=1, verbose_name='Estado de la Sede'),
        ),
    ]
