# Generated by Django 4.0.3 on 2022-04-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0004_alter_sede_estado_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observacion', models.CharField(default='', max_length=100, verbose_name='Observaciones')),
                ('temp_almacenamiento', models.CharField(default='22', max_length=5, verbose_name='Temperatura de almacenamiento')),
                ('bodega', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vmi.bodega')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.referencia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
