# Generated by Django 4.0.3 on 2022-03-24 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0005_referencia_alter_bodega_idbodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fechaFactura',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 14, 10, 1, 582615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='movinventario',
            name='fechaMov',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 14, 10, 1, 583873, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 14, 10, 1, 582960, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pedidosmov',
            name='fecha_pedido',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 14, 10, 1, 583164, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 24, 14, 10, 1, 581325, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='idReferencia',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
