# Generated by Django 4.0.3 on 2022-04-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0005_saldohistorico_saldoactual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre_ciudad'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='saldoactual',
            options={'verbose_name': 'Saldo Actual', 'verbose_name_plural': 'Saldos Actuales'},
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre_ciudad',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.saldoactual'),
        ),
        migrations.AlterField(
            model_name='saldoactual',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.bodega'),
        ),
        migrations.AlterField(
            model_name='saldoactual',
            name='observacion',
            field=models.CharField(default='C', max_length=100, verbose_name='Observaciones'),
        ),
    ]
