# Generated by Django 4.0.3 on 2022-04-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0005_alter_bodega_estado_alter_sede_estado_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_fac', 'Permisos de CRUD para crear y editar facturas')], 'verbose_name': 'Detalle de Factura', 'verbose_name_plural': 'Detalles de Facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_fac', 'Permisos de CRUD para crear y editar facturas')], 'verbose_name': 'Encabezado de Factura', 'verbose_name_plural': 'Encabezados de Facturas'},
        ),
    ]
