# Generated by Django 4.0.3 on 2022-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0006_alter_facturadet_options_alter_facturaenc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotipo',
            name='estado',
            field=models.CharField(choices=[('Entrada_Bodega', 'Entrada de Bodega'), ('Salida_Bodega', 'Salida de Bodega')], default='Entrada de Bodega', max_length=14),
        ),
    ]
