# Generated by Django 4.0.3 on 2022-03-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0007_alter_factura_fechafactura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturasmov',
            old_name='ideReferencia',
            new_name='idReferencia',
        ),
    ]
