# Generated by Django 4.0.3 on 2022-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0007_movimientotipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientotipo',
            name='nombre_mov',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
