# Generated by Django 4.0.3 on 2022-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0009_alter_pedidosmov_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
