# Generated by Django 4.0.3 on 2022-03-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0010_referencia_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_dane', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_dane', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidosmov',
            name='valor_de_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidosmov',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SaldoHistorico',
            fields=[
                ('id_referencia', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_corte', models.DateTimeField()),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoActual',
            fields=[
                ('id_referencia', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_mov', models.DateTimeField(auto_now_add=True)),
                ('id_bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_dane', models.CharField(max_length=50)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmi.pais'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='id_municipio',
            field=models.ForeignKey(default=800, on_delete=django.db.models.deletion.CASCADE, to='vmi.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='id_municipio',
            field=models.ForeignKey(default=800, on_delete=django.db.models.deletion.CASCADE, to='vmi.municipio'),
            preserve_default=False,
        ),
    ]
