# Generated by Django 4.0.3 on 2022-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0011_departamento_pais_pedido_valor_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='id_municipio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
