# Generated by Django 4.0.3 on 2022-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0012_alter_municipio_id_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipounidad',
            name='idUnidad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
