# Generated by Django 4.0.3 on 2022-03-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0013_alter_tipounidad_idunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='idReferencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
