# Generated by Django 4.0.3 on 2022-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0014_alter_referencia_idreferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='saldo',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
