# Generated by Django 4.0.3 on 2022-04-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0015_alter_inventario_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inhabilitado'), ('C', 'Cancelado'), ('S', 'Suspendido')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
