# Generated by Django 4.0.3 on 2022-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmi', '0016_proveedor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inhabilitado'), ('C', 'Cancelado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
